"""`Laya`: the public entry point.

    from laya_apple import Laya
    laya = Laya.from_pretrained("convaiinnovations/laya-typed-decisions")
    result = laya.predict(context="...", questions={...})
    result.answers, result.runtime

Two execution modes:

- execution="inline" (default): the backends live in this process and requests run one
  at a time per instance. Routing is the v0.1 rule (routing.decide).
- execution="workers": each device's backend runs in its own worker process
  (laya_apple.executor), so the GPU and the ANE serve requests concurrently without the
  in-process interference measured in research/v0.2-concurrency. `predict` may be called
  from many threads; `submit` returns a Future and `apredict` is awaitable. Routing is
  queue-aware (scheduling.decide_queued), and identical to v0.1 on an idle machine.
"""

from __future__ import annotations

import asyncio
import dataclasses
import itertools
import json
import threading
import time
import warnings
from concurrent.futures import Future
from pathlib import Path

from . import routing, scheduling
from .artifacts import platform_profile, profile_matches
from .errors import (
    ArtifactMissingError,
    BackendUnavailableError,
    InvalidRequestError,
    LayaAppleError,
)
from .hub import checkpoint_path, verify_weights
from .prompt import Calibration, Tokenizer, format_answers, prepare
from .registry import ANE_COMPUTE_UNITS, ANE_PRECISION, DTYPES, ModelSpec, resolve, routing_table
from .result import Result, RuntimeInfo
from .trace import QueueSnapshot, RequestTrace, TraceCallback

EXECUTIONS = ("inline", "workers")
ANE_PLACEMENTS = ("auto", "thread", "process")
ANE_STARTUPS = ("wait", "background")
# `questions={}` is answered without a device, as upstream v0.3.20 does (empty answers, zero
# usage). Its RuntimeInfo says so: backend and device "none", this routing reason, no trace.
NO_QUESTIONS = "no_questions"
# Request ids are unique within the process, across Laya instances, so traces, worker-side
# records and logs from several instances join on the id alone.
_REQUEST_IDS = itertools.count(1)


def ane_placement_for(model: str) -> str:
    """Measured per-model ANE placement for execution="workers" (laya_apple/data/placement.json,
    generated by scripts/derive_placement.py from benchmarks/v0.2/placement-*.json)."""
    from importlib import resources

    table = json.loads(resources.files("laya_apple.data").joinpath("placement.json").read_text())
    return table["models"][model]["ane"]


def _check_ane_handoff(ane_handoff, model: str, execution: str, device: str, ane_placement: str) -> None:
    """Raise ValueError unless ane_handoff is False, or True on an eligible configuration:
    execution="workers", device="auto", and the ANE on a thread by this model's measured
    placement (not an override: laya-multilingual's is "process", and never uses it)."""
    if ane_handoff is not True and ane_handoff is not False:
        raise ValueError(f"ane_handoff must be True or False, got {ane_handoff!r}")
    if not ane_handoff:
        return
    measured = ane_placement_for(model)
    placement = measured if ane_placement == "auto" else ane_placement
    if execution != "workers" or device != "auto" or placement != "thread" or measured != "thread":
        raise ValueError(
            'ane_handoff=True applies only to execution="workers", device="auto" with the ANE on a thread by '
            f"the model's measured placement ({model}: {measured!r}; requested {ane_placement!r})"
        )


def _coremltools_available() -> bool:
    try:
        import coremltools  # noqa: F401
    except ImportError:
        return False
    return True


def platform_validated(profile: dict | None = None) -> bool:
    profile = profile or platform_profile()
    return any(profile_matches(profile, p) for p in routing_table().get("validated_profiles", []))


class _GPUView:
    """Parent-side identity of an MLX worker (for RuntimeInfo)."""

    name, device = "mlx", "gpu"

    def __init__(self, spec: ModelSpec, dtype: str):
        self.spec, self.dtype = spec, dtype

    def artifact_revision(self, items) -> str:
        return f"mlx:{self.spec.weights_sha256[:12]}:{self.dtype}"


class Laya:
    """A loaded checkpoint plus the backends its `device` setting allows."""

    ane_handoff = False  # the staged Core ML handoff (opt-in); set per instance by __init__
    _handoff = None

    def __init__(
        self,
        spec: ModelSpec,
        checkpoint: Path,
        device: str,
        *,
        dtype: str,
        batch_size: int,
        execution: str = "inline",
        ane_placement: str = "auto",
        ane_startup: str = "wait",
        trace: TraceCallback | None = None,
        ane_handoff: bool = False,
    ):
        if device not in routing.DEVICES:
            raise ValueError(f"device must be one of {routing.DEVICES}, got {device!r}")
        if execution not in EXECUTIONS:
            raise ValueError(f"execution must be one of {EXECUTIONS}, got {execution!r}")
        if dtype not in DTYPES:
            raise ValueError(f"dtype must be one of {DTYPES}, got {dtype!r}")
        if device == "ane" and dtype != ANE_PRECISION:
            # The ANE artifacts are validated in ANE_PRECISION only; never run another silently.
            raise ValueError(f"device='ane' runs {ANE_PRECISION} only; dtype={dtype!r} is not validated on the ANE")
        self.spec, self.checkpoint, self.device, self.dtype = spec, checkpoint, device, dtype
        self.execution = execution
        if trace is not None and execution != "workers":
            raise ValueError('trace applies only to execution="workers"')
        self._trace = trace
        self._trace_warned = False
        if ane_startup not in ANE_STARTUPS:
            raise ValueError(f"ane_startup must be one of {ANE_STARTUPS}, got {ane_startup!r}")
        if ane_startup == "background" and (execution != "workers" or device != "auto"):
            raise ValueError('ane_startup="background" applies only to execution="workers", device="auto"')
        self.ane_startup = ane_startup
        self._ane_thread = None
        if ane_placement not in ANE_PLACEMENTS:
            raise ValueError(f"ane_placement must be one of {ANE_PLACEMENTS}, got {ane_placement!r}")
        self.ane_placement = ane_placement_for(spec.name) if ane_placement == "auto" else ane_placement
        _check_ane_handoff(ane_handoff, spec.name, execution, device, ane_placement)
        self.ane_handoff = ane_handoff
        self._handoff = None  # laya_apple.handoff.StagedHandoff when the staged handoff is in use
        self.config = json.loads((checkpoint / "rl_agent_config.json").read_text())
        self._encoder_cfg = json.loads((checkpoint / "encoder/config.json").read_text())
        self.tokenizer = Tokenizer(checkpoint / "tokenizer")
        self.calibration = Calibration(self.config)
        self.mlx = self.ane = None  # backends (inline) or parent-side views (workers)
        self._workers: dict = {}
        self._tie_buckets: tuple = ()
        self.routing_profile, service = self._routing_profile()
        self._service = scheduling.ServiceModel(service)
        self.ane_state = routing.AneState(routing.RUNTIME_UNAVAILABLE)
        # Inline: one request at a time per instance; Core ML predictions and MLX graph
        # evaluation on a shared model are not documented as re-entrant.
        self._lock = threading.Lock()
        self._closed = False
        self._ane_dead_warned = False
        try:
            if execution == "inline":
                self._start_inline(batch_size)
            else:
                self._start_workers(batch_size)
        except BaseException:
            self.close()
            raise

    # ------------------------------------------------------------------ construction

    @classmethod
    def from_pretrained(
        cls,
        model_id: str,
        device: str = "auto",
        *,
        dtype: str = "float16",
        local_files_only: bool = False,
        batch_size: int = 16,
        execution: str = "inline",
        ane_placement: str = "auto",
        ane_startup: str = "wait",
        trace: TraceCallback | None = None,
        ane_handoff: bool = False,
    ) -> "Laya":
        """Load a pinned checkpoint.

        device="gpu": MLX only. device="ane": validated Core ML artifacts only; requests
        they cannot serve raise. device="auto": MLX, plus the ANE for the validated short
        single-question path when its artifacts are present and verified (§7.2).
        execution="workers" serves both devices concurrently (heterogeneous execution): MLX
        in a worker process, Core ML either on a thread in this process or in a worker
        process. ane_placement="auto" uses the measured per-model choice.
        ane_startup="background" (workers, auto): return once MLX is ready and finish loading
        the ANE artifacts (and any evicted ANE compile) in the background; until then auto
        routes to MLX with reason "ane_starting".
        trace (workers only): called with one laya_apple.trace.RequestTrace per completed
        request (see laya_apple/trace.py); None, the default, records nothing.
        ane_handoff: opt in to the staged Core ML handoff of an in-process ANE
        (laya_apple/handoff.py, docs/guide.md). False, the default, is the path of earlier
        releases. True needs execution="workers", device="auto" and a model whose ANE runs on
        a thread (ValueError otherwise, before anything loads), plus both devices started,
        pyobjc-framework-CoreML, and asynchronous models that pass their load checks
        (BackendUnavailableError otherwise).
        """
        if device not in routing.DEVICES:
            raise ValueError(f"device must be one of {routing.DEVICES}, got {device!r}")
        if execution not in EXECUTIONS:
            raise ValueError(f"execution must be one of {EXECUTIONS}, got {execution!r}")
        spec = resolve(model_id)
        if ane_handoff is not False:  # checked before any download; the default path is unchanged
            if ane_placement not in ANE_PLACEMENTS:
                raise ValueError(f"ane_placement must be one of {ANE_PLACEMENTS}, got {ane_placement!r}")
            _check_ane_handoff(ane_handoff, spec.name, execution, device, ane_placement)
        path = checkpoint_path(spec, local_files_only=local_files_only)
        verify_weights(spec, path)
        return cls(
            spec,
            path,
            device,
            dtype=dtype,
            batch_size=batch_size,
            execution=execution,
            ane_placement=ane_placement,
            ane_startup=ane_startup,
            trace=trace,
            ane_handoff=ane_handoff,
        )

    def _routing_profile(self):
        """Which measured routing table applies on this machine.

        The shipped table if a shipped profile matches; otherwise a local calibration for
        this exact profile (laya-apple calibrate), which also replaces the auto buckets;
        otherwise none, and auto uses MLX only."""
        from .profiles import load_local

        shipped = routing_table()["models"][self.spec.name]["service_ms"]
        if platform_validated():
            return "shipped", shipped
        local = load_local(self.spec.name)
        if local is None:
            return None, shipped
        buckets = tuple(local.get("auto_ane_buckets") or ())
        if buckets != self.spec.ane_buckets[: len(buckets)]:
            warnings.warn(
                f"laya-apple: ignoring local profile {local['source']}: its auto buckets {list(buckets)} are not "
                f"a prefix of the offered buckets {list(self.spec.ane_buckets)} for {self.spec.name}; "
                "re-run laya-apple calibrate",
                RuntimeWarning,
                stacklevel=4,
            )
            return None, shipped
        self.spec = dataclasses.replace(
            self.spec,
            auto_ane_buckets=tuple(local["auto_ane_buckets"]),
            auto_ane_max_len=int(local["auto_ane_max_len"]),
            auto_ane_max_questions=int(local["auto_ane_max_questions"]),
        )
        return f"local:{local['source']}", local["service_ms"]

    def _ane_gate(self) -> str | None:
        """Why auto cannot use the ANE here, or None."""
        if not _coremltools_available():
            return routing.RUNTIME_UNAVAILABLE
        if self.routing_profile is None:
            return routing.PLATFORM_NOT_VALIDATED
        return None

    def _warn_rejected(self, load_errors: dict):
        for b, e in load_errors.items():
            if not isinstance(e, ArtifactMissingError):
                warnings.warn(
                    f"laya-apple: ANE artifact {self.spec.name} L{b} rejected ({type(e).__name__}: {e}); "
                    "auto routes these requests to MLX",
                    RuntimeWarning,
                    stacklevel=5,
                )

    def _start_inline(self, batch_size):
        if self.device in ("auto", "gpu"):
            from .backends.mlx import MLXBackend

            self.mlx = MLXBackend(
                self.spec, self.checkpoint, self.tokenizer.pad_token_id, dtype=self.dtype, batch_size=batch_size
            )
        if self.device == "ane":
            self.ane = self._load_ane_inline(self.spec.ane_buckets, strict=True)
            self.ane_state = routing.AneState(None, self.ane.buckets)
        elif self.device == "auto":
            if not self.spec.auto_ane_buckets:
                self.ane_state = routing.AneState(None, ())
            elif (why := self._ane_gate()) is not None:
                self.ane_state = routing.AneState(why)
            else:
                self.ane = self._load_ane_inline(self.spec.auto_ane_buckets, strict=False)
                self._warn_rejected(self.ane.load_errors)
                if not self.ane.models:
                    self.ane = None
                self.ane_state = routing.AneState(None, self.ane.buckets if self.ane else ())

    def _load_ane_inline(self, buckets, *, strict):
        if not _coremltools_available():
            raise BackendUnavailableError(
                "device='ane' needs coremltools: install the [ane] extra (uv sync --extra ane)"
            )
        from .backends.coreml_ane import ANEBackend

        return ANEBackend(
            self.spec,
            self.checkpoint,
            self.tokenizer.pad_token_id,
            int(self._encoder_cfg["local_attention"]),
            buckets,
            strict=strict,
        )

    def _start_workers(self, batch_size):
        from .executor import DeviceWorker

        common = {"model": self.spec.name, "checkpoint": str(self.checkpoint), "pad_id": self.tokenizer.pad_token_id}
        want_ane = self.device == "ane"
        if self.device == "auto":
            if not self.spec.ane_buckets:
                self.ane_state = routing.AneState(None, ())
            elif (why := self._ane_gate()) is not None:
                self.ane_state = routing.AneState(why)
            else:
                want_ane = True
        elif self.device == "ane" and not _coremltools_available():
            raise BackendUnavailableError(
                "device='ane' needs coremltools: install the [ane] extra (uv sync --extra ane)"
            )
        gpu_activity = self._handoff_activity(want_ane)
        # Launch every worker first, then wait: the devices load in parallel.
        if want_ane:
            ane_args = dict(
                common,
                local_attention=int(self._encoder_cfg["local_attention"]),
                buckets=list(self.spec.ane_buckets),  # auto also loads the tie band for queue-aware routing
                strict=self.device == "ane",
            )
            if gpu_activity is not None:
                ane_args["async_models"] = True
            self._workers["ane"] = DeviceWorker("ane", ane_args, placement=self.ane_placement, wait=False)
        if self.device in ("auto", "gpu"):
            gpu_args = dict(common, dtype=self.dtype, batch_size=batch_size)
            self._workers["gpu"] = DeviceWorker("gpu", gpu_args, placement="process", wait=False)
            if gpu_activity is not None:
                self._workers["gpu"].activity = gpu_activity  # before any submit
        background = want_ane and self.ane_startup == "background"
        for kind, w in self._workers.items():
            if not (background and kind == "ane"):
                w.wait_ready()
        if "gpu" in self._workers:
            self.mlx = _GPUView(self.spec, self.dtype)
        if background:
            self.ane_state = routing.AneState(routing.ANE_STARTING)
            self._ane_thread = threading.Thread(
                target=self._finish_ane_background, name="laya-ane-startup", daemon=True
            )
            self._ane_thread.start()
        elif want_ane:
            self._finish_ane()

    def _handoff_activity(self, want_ane: bool):
        """With ane_handoff=True (arguments already checked by _check_ane_handoff), create the
        staged handoff and return the GpuActivity the GPU worker feeds, or raise
        BackendUnavailableError when this machine cannot run it. With False (the default),
        None: nothing is imported or loaded for it."""
        if not self.ane_handoff:
            return None
        if not want_ane:
            why = f"the ANE is not started ({self.ane_state.unavailable or 'no ANE bucket for this model'})"
        else:
            from .backends.coreml_async import unavailable_reason

            why = unavailable_reason()
        if why is not None:
            raise BackendUnavailableError(f"ane_handoff=True cannot be used: {why}")
        from .handoff import GpuActivity, StagedHandoff

        activity = GpuActivity()
        self._handoff = StagedHandoff(activity)
        return activity

    def _attach_handoff(self, worker) -> None:
        """Give the loaded in-process ANE backend the staged handoff, or raise
        BackendUnavailableError if its asynchronous Core ML models did not load or failed their
        load checks (ane_handoff=True asked for them)."""
        handoff, backend = self._handoff, worker._backend
        if handoff is None:
            return
        error = getattr(backend, "async_error", None)
        if error is not None or not getattr(backend, "async_models", None):
            reason = f"{type(error).__name__}: {error}" if error is not None else "no async Core ML model loaded"
            handoff.disable(f"async Core ML load failed: {reason}")
            raise BackendUnavailableError(f"ane_handoff=True: the asynchronous Core ML path is unavailable: {reason}")
        backend.handoff = handoff

    def _finish_ane_background(self):
        try:
            self._workers["ane"].wait_ready()
            if self._closed:
                return
            self._finish_ane()
        except BaseException as e:  # reported, and auto keeps using MLX
            if self._closed:  # close() during start-up is not a start-up failure
                return
            warnings.warn(
                f"laya-apple: ANE startup failed ({type(e).__name__}: {e}); auto routes to MLX",
                RuntimeWarning,
                stacklevel=2,
            )
            worker = self._workers.pop("ane", None)
            if worker is not None:
                worker.close()
            if self._handoff is not None:
                self._handoff.disable("ANE startup failed")
            self.ane_state = routing.AneState(routing.RUNTIME_UNAVAILABLE)

    def _finish_ane(self):
        from .backends.coreml_ane import ANEShapes

        worker = self._workers["ane"]
        info = worker.info
        load_errors = {int(b): e for b, e in info["load_errors"].items()}
        shapes = ANEShapes(
            self.spec, info["offered"], {int(b): h for b, h in info["artifact_sha256"].items()}, load_errors
        )
        shapes.probes = {int(b): v for b, v in info.get("probes", {}).items()}
        if self.device == "auto":
            self._warn_rejected(load_errors)
        if shapes.buckets:
            self._attach_handoff(worker)  # before auto routing can send a request to the ANE
            self.ane = shapes
            auto = tuple(b for b in shapes.buckets if b in self.spec.auto_ane_buckets)
            self._tie_buckets = tuple(b for b in shapes.buckets if b not in self.spec.auto_ane_buckets)
            self.ane_state = routing.AneState(None, auto if self.device == "auto" else shapes.buckets)
        else:
            self._workers.pop("ane").close()
            if self._handoff is not None:
                self._handoff.disable("no ANE bucket loaded")
                raise BackendUnavailableError("ane_handoff=True: no ANE bucket loaded")
            self.ane_state = routing.AneState(None, ())

    def wait_for_ane(self, timeout: float | None = None) -> bool:
        """With ane_startup="background": block until the ANE finished starting (or failed).
        Returns whether the ANE path is available to auto routing."""
        if self._ane_thread is not None:
            self._ane_thread.join(timeout)
        return self.ane is not None and self.ane_state.unavailable is None

    # ------------------------------------------------------------------ lifecycle

    def close(self):
        """Stop worker processes (workers mode). Safe to call more than once."""
        if self._closed:
            return
        self._closed = True
        for w in list(self._workers.values()):  # the background ANE start-up may pop concurrently
            try:
                w.close()
            except Exception:
                pass
        self._workers = {}
        if self._ane_thread is not None and self._ane_thread is not threading.current_thread():
            self._ane_thread.join(timeout=30)

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass

    # ------------------------------------------------------------------ inference

    def queue_snapshots(self):
        """(gpu, ane) QueueSnapshot, each None without a ready worker (always None inline)."""
        gpu, ane = self._workers.get("gpu"), self._workers.get("ane")  # "ane" may be popped concurrently
        return (gpu.snapshot() if gpu else None), (ane.snapshot() if ane else None)

    def backlogs(self) -> tuple[float, float]:
        """(gpu, ane) backlog estimates in ms; zeros in inline mode."""
        gpu, ane = self.queue_snapshots()
        return (gpu.backlog_ms if gpu else 0.0), (ane.backlog_ms if ane else 0.0)

    def route(self, prepared, backlogs: tuple[float, float] | None = None) -> routing.Decision:
        if self.execution == "inline":
            return routing.decide(
                self.device, self.spec, prepared.question_count, prepared.sequence_length, self.ane_state
            )
        gpu_backlog, ane_backlog = backlogs if backlogs is not None else self.backlogs()
        ane_state = self.ane_state
        worker = self._workers.get("ane")
        if self.device == "auto" and worker is not None and not worker.alive:
            # A dead ANE worker is reported, never hidden: auto records the reason on every
            # result and warns once; explicit device="ane" requests keep raising.
            if not self._ane_dead_warned:
                self._ane_dead_warned = True
                warnings.warn(
                    "laya-apple: the ANE worker exited; auto routes to MLX (ane_runtime_unavailable)",
                    RuntimeWarning,
                    stacklevel=3,
                )
            ane_state = routing.AneState(routing.RUNTIME_UNAVAILABLE)
        return scheduling.decide_queued(
            self.device,
            self.spec,
            prepared.question_count,
            prepared.sequence_length,
            ane_state,
            service=self._service,
            gpu_backlog_ms=gpu_backlog,
            ane_backlog_ms=ane_backlog,
            tie_buckets=self._tie_buckets,
        )

    def prepare(self, context, questions):
        return prepare(self.tokenizer, self.config, context, questions)

    @staticmethod
    def _request(context, questions, state):
        if state is not None:
            if context is not None:
                raise InvalidRequestError("pass context or state, not both")
            context = state
        if context is None:
            context = ""
        if questions is None:
            raise InvalidRequestError("questions are required")
        return context, questions

    def predict(self, context=None, questions=None, *, state=None) -> Result:
        """Answer `questions` about `context` (upstream calls it `state`; either works)."""
        if self.execution == "workers":
            return self.submit(context, questions, state=state).result()
        context, questions = self._request(context, questions, state)
        t0 = time.monotonic_ns()
        request_id = next(_REQUEST_IDS)
        prep = self.prepare(context, questions)
        if not prep.items:
            return self._empty_result(t0, request_id)
        decision = self.route(prep)
        backend = self.ane if decision.target == "ane" else self.mlx
        if backend is None:  # unreachable by construction; never substitute another device
            raise LayaAppleError(f"internal routing error: {decision}")
        buckets = ()
        with self._lock:
            if decision.target == "ane":
                buckets = tuple(backend.check(prep.items))  # raises before any work runs
            logits, act = backend.forward(prep.items)
        answers = format_answers(prep, logits, act, self.calibration)
        return self._result(prep, decision, backend, buckets, answers, t0, time.monotonic_ns(), request_id)

    def submit(self, context=None, questions=None, *, state=None) -> Future:
        """Queue a request; the Future resolves to a Result or raises the request's error."""
        if self.execution == "inline":
            fut: Future = Future()
            try:
                fut.set_result(self.predict(context, questions, state=state))
            except BaseException as e:
                fut.set_exception(e)
            return fut
        if self._closed:
            raise BackendUnavailableError("this Laya instance is closed")
        context, questions = self._request(context, questions, state)
        t0 = time.monotonic_ns()
        request_id = next(_REQUEST_IDS)
        trace = self._trace
        prep = self.prepare(context, questions)
        if not prep.items:
            done: Future = Future()
            done.set_result(self._empty_result(t0, request_id))
            return done
        prepared_ns = time.monotonic_ns() if trace is not None else 0
        # One reading per device: the router decides on it and the trace records the same values.
        gpu_w, ane_w = self._workers.get("gpu"), self._workers.get("ane")  # "ane" may be popped concurrently
        gpu_q = gpu_w.read_queue() if gpu_w else None
        ane_q = ane_w.read_queue() if ane_w else None
        gpu_backlog = gpu_q[0] if gpu_q else 0.0
        ane_backlog = ane_q[0] if ane_q else 0.0
        decision = self.route(prep, (gpu_backlog, ane_backlog))
        routed_ns = time.monotonic_ns() if trace is not None else 0
        backend = self.ane if decision.target == "ane" else self.mlx
        worker = self._workers.get(decision.target)
        if backend is None or worker is None:  # unreachable by construction; never substitute
            raise LayaAppleError(f"internal routing error: {decision}")
        buckets = ()
        if decision.target == "ane":
            buckets = tuple(backend.check(prep.items))  # raises before any work is queued
            estimate = sum(self._service.ane_ms(b) for b in buckets)
        else:
            estimate = self._service.gpu_ms(prep.sequence_length, prep.question_count)
        out: Future = Future()

        def finish(done: Future):  # runs on the dispatcher thread as it resolves the device job
            received_ns = time.monotonic_ns() if trace is not None else 0
            try:
                logits, act, enq_ns, dispatch_ns, start_ns, end_ns = done.result()
                answers = format_answers(prep, logits, act, self.calibration)
                response_ns = time.monotonic_ns()
                result = self._result(
                    prep,
                    decision,
                    backend,
                    buckets,
                    answers,
                    t0,
                    response_ns,
                    request_id,
                    wait_ms=(dispatch_ns - enq_ns) / 1e6,
                    device_ms=(end_ns - start_ns) / 1e6,
                    gpu_backlog_ms=gpu_backlog,
                    ane_backlog_ms=ane_backlog,
                )
                if trace is not None:
                    self._emit(
                        trace,
                        RequestTrace(
                            request_id=request_id,
                            sequence_length=prep.sequence_length,
                            question_count=prep.question_count,
                            target=decision.target,
                            routing_reason=decision.reason,
                            service_estimate_ms=estimate,
                            gpu=QueueSnapshot._make(gpu_q) if gpu_q else None,
                            ane=QueueSnapshot._make(ane_q) if ane_q else None,
                            submit_ns=t0,
                            prepared_ns=prepared_ns,
                            routed_ns=routed_ns,
                            queue_enter_ns=enq_ns,
                            dispatch_ns=dispatch_ns,
                            service_start_ns=start_ns,
                            service_end_ns=end_ns,
                            received_ns=received_ns,
                            response_ns=response_ns,
                        ),
                    )
                if not out.cancelled():  # the caller may have given up (asyncio cancellation)
                    out.set_result(result)
            except BaseException as e:
                if not out.cancelled():
                    out.set_exception(e)

        worker.submit(prep.items, estimate, request_id).add_done_callback(finish)
        return out

    def _emit(self, callback: TraceCallback, trace: RequestTrace) -> None:
        """Hand one trace to the callback; its failure is reported once, never raised."""
        try:
            callback(trace)
        except Exception as e:
            if not self._trace_warned:
                self._trace_warned = True
                warnings.warn(
                    f"laya-apple: the trace callback raised {type(e).__name__}: {e}; requests are unaffected "
                    "(reported once per instance)",
                    RuntimeWarning,
                    stacklevel=2,
                )

    async def apredict(self, context=None, questions=None, *, state=None) -> Result:
        """Awaitable predict (workers mode runs concurrently; inline mode runs in a thread)."""
        if self.execution == "inline":
            return await asyncio.to_thread(self.predict, context, questions, state=state)
        return await asyncio.wrap_future(self.submit(context, questions, state=state))

    def _result(
        self,
        prep,
        decision,
        backend,
        buckets,
        answers,
        t0_ns,
        end_ns,
        request_id,
        *,
        wait_ms=None,
        device_ms=None,
        gpu_backlog_ms=None,
        ane_backlog_ms=None,
    ) -> Result:
        runtime = RuntimeInfo(
            backend=backend.name,
            device=backend.device,
            model=self.spec.name,
            model_revision=self.spec.revision,
            sequence_length=prep.sequence_length,
            question_count=prep.question_count,
            routing_reason=decision.reason,
            artifact_revision=backend.artifact_revision(prep.items),
            latency_ms=(end_ns - t0_ns) / 1e6,
            compute_units=ANE_COMPUTE_UNITS if decision.target == "ane" else None,
            buckets=buckets,
            dtype=ANE_PRECISION if decision.target == "ane" else self.dtype,
            execution=self.execution,
            queue_wait_ms=wait_ms,
            device_ms=device_ms,
            gpu_backlog_ms=gpu_backlog_ms,
            ane_backlog_ms=ane_backlog_ms,
            request_id=request_id,
            truncated=prep.truncated,
        )
        return Result(answers=answers, usage={"input_tokens": prep.input_tokens, "output_tokens": 0}, runtime=runtime)

    def _empty_result(self, t0_ns, request_id) -> Result:
        """`questions={}`: no tokenization, routing, device work or trace; nothing ran anywhere."""
        runtime = RuntimeInfo(
            backend="none",
            device="none",
            model=self.spec.name,
            model_revision=self.spec.revision,
            sequence_length=0,
            question_count=0,
            routing_reason=NO_QUESTIONS,
            artifact_revision="",
            latency_ms=(time.monotonic_ns() - t0_ns) / 1e6,
            execution=self.execution,
            request_id=request_id,
        )
        return Result(answers={}, usage={"input_tokens": 0, "output_tokens": 0}, runtime=runtime)

    def info(self) -> dict:
        info = {
            "model": self.spec.name,
            "repo": self.spec.repo,
            "revision": self.spec.revision,
            "device": self.device,
            "execution": self.execution,
            "ane_placement": self.ane_placement if self.execution == "workers" else None,
            "dtype": self.dtype,
            "mlx": self.mlx is not None,
            "ane_buckets": list(self.ane.buckets) if self.ane else [],
            "ane_load_errors": {
                str(b): f"{type(e).__name__}: {e}" for b, e in (self.ane.load_errors.items() if self.ane else [])
            },
            "ane_probes": {str(b): v for b, v in getattr(self.ane, "probes", {}).items()},
            "routing_profile": self.routing_profile,
            "ane_ready": bool(self.ane) and self.ane_state.unavailable is None,
            "auto_ane": {
                "unavailable": self.ane_state.unavailable,
                "buckets": list(self.ane_state.buckets),
                "tie_buckets": list(self._tie_buckets),
            },
        }
        if self.ane_handoff:  # opt-in only: info() is unchanged without it
            info["ane_handoff"] = self._handoff.snapshot() if self._handoff is not None else None
        return info
