"""Background load before each window of the slow-state trigger runs: background.md from raw/.

    python research/coreml-slow-state-trigger/scripts/background.py [--check]

Reads `part_a.windows[*].conditions_before` of raw/laya-<cell>-r<round>.json.gz, which
scripts/bench_concurrency.py `conditions()` writes once before each window (after the 2.0 s idle, before
the 0.5 s lead): the machine's load averages and the five processes with the highest `ps -Ao %cpu=`. It
reduces them per cell, per window group and per process. Descriptive only: it changes no outcome and
applies no rule, and it does not use analyze.py's decision. The raw files are external evidence
(../evidence.json), fetched to raw/ first. Standard library only. --raw / --out exist for checking the
reduction on files kept elsewhere.
"""

from __future__ import annotations

import argparse
import gzip
import importlib.util
import json
import re
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
EXP = HERE.parent


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


design = _load("slow_state_design_bg", HERE / "design.py")  # for CELLS, MODEL and is_slow (the 13.0 ms split)

CELL_RE = "|".join(re.escape(c) for c in design.CELLS)
RUN_NAME = re.compile(rf"^{design.MODEL}-(?P<cell>{CELL_RE})-r(?P<round>\d+)\.json\.gz$")
GROUPS = (
    "hetero, PB-R, slow",
    "hetero, PB-R, normal",
    "hetero, other cells, slow",
    "hetero, other cells, normal",
    "not hetero, all cells",
)


def group_of(cell: str, condition: str, slow: bool | None) -> str:
    if condition != "hetero":
        return GROUPS[4]
    return f"hetero, {'PB-R' if cell == 'PB-R' else 'other cells'}, {'slow' if slow else 'normal'}"


def windows(raw: Path) -> list[dict]:
    """One record per window of every run: its group, the load averages and the (percent, process) samples."""
    out = []
    for p in sorted(raw.glob(f"{design.MODEL}-*-r*.json.gz")):
        if not (x := RUN_NAME.match(p.name)):
            continue
        with gzip.open(p, "rt") as fh:
            run = json.load(fh)
        for w in run["part_a"]["windows"]:
            hetero = w["condition"] == "hetero"
            p99 = w["streams"]["short"]["p99_ms"] if hetero else None
            slow = design.is_slow(p99) if hetero else None
            before = w["conditions_before"]
            best: dict[str, float] = {}  # one entry per process name and window: its highest sample
            for pct, name in before["top_cpu"]:
                best[name] = max(best.get(name, 0.0), pct)
            out.append(
                {
                    "run": p.name[: -len(".json.gz")],
                    "cell": x["cell"],
                    "cycle": w["cycle"],
                    "condition": w["condition"],
                    "slow": slow,
                    "p99": p99,
                    "group": group_of(x["cell"], w["condition"], slow),
                    "load": before["loadavg"],
                    "top": [(pct, name) for pct, name in before["top_cpu"]],
                    "best": best,
                }
            )
    return out


def _range(values, nd: int) -> str:
    return f"{min(values):.{nd}f} to {max(values):.{nd}f}"


def tables(ws: list[dict]) -> str:
    groups = [g for g in GROUPS if any(w["group"] == g for w in ws)]
    L = [
        "# Background load before each window",
        "",
        "Descriptive, not part of the outcome. Generated by `scripts/background.py` from `part_a.windows[*].conditions_before` "
        f"of the {len({w['run'] for w in ws})} raw runs in [`evidence.json`](evidence.json) ({len(ws)} windows). "
        "`bench_concurrency.py` samples once before each window, after the 2.0 s idle and before the 0.5 s lead, so nothing "
        "is sampled during a window.",
        "",
        "- **Load averages** are the machine's 1, 5 and 15 minute figures at that moment. They include this run's own "
        "threads from the windows before.",
        "- **Processes** are the five with the highest `ps -Ao %cpu=`, named by the last path component of `comm`. "
        "`ps` `%cpu` is a decaying average over up to a minute of earlier time, with 100 as one core, so a value says a "
        "process was recently busy, not that it ran during the window. A process outside the five is not recorded, and "
        "`python` and `claude` are process names as recorded; the data do not say which instance.",
        "- **Windows** are grouped by type. A hetero window is slow if its short P99 is at least "
        f"{design.SLOW_P99_MS:g} ms (as in `tables.md`); the other window types have no state.",
        "",
        "## Load averages per cell",
        "",
        "| cell | window group | windows | 1 min | 5 min | 15 min |",
        "|---|---|---|---|---|---|",
    ]
    for cell in design.CELLS:
        for label, pick in (
            ("hetero, slow", lambda w: w["condition"] == "hetero" and w["slow"]),
            ("hetero, normal", lambda w: w["condition"] == "hetero" and not w["slow"]),
            ("not hetero", lambda w: w["condition"] != "hetero"),
        ):
            sel = [w for w in ws if w["cell"] == cell and pick(w)]
            if sel:
                rng = " | ".join(_range([w["load"][i] for w in sel], 2) for i in range(3))
                L.append(f"| {cell} | {label} | {len(sel)} | {rng} |")
    L += ["", "## Processes in the top five, per window group", "", "Each cell is the number of windows the process "
          "appears in, then its `%cpu` range (its highest sample per window).", ""]
    L.append("| process | " + " | ".join(f"{g} ({sum(w['group'] == g for w in ws)})" for g in groups) + f" | all ({len(ws)}) |")
    L.append("|---|" + "---|" * (len(groups) + 1))
    names = sorted({n for w in ws for n in w["best"]}, key=lambda n: (-sum(n in w["best"] for w in ws), n))
    for n in names:
        cells = []
        for sel in [[w for w in ws if w["group"] == g] for g in groups] + [ws]:
            hit = [w["best"][n] for w in sel if n in w["best"]]
            cells.append(f"{len(hit)}: {_range(hit, 1)}" if hit else "-")
        L.append(f"| `{n}` | " + " | ".join(cells) + " |")
    L += ["", "## Highest recorded `%cpu` in a window's sample", "",
          "The 20 and 50 columns count windows with a process at or above that `%cpu`; the cut points are arbitrary.", "",
          "| window group | windows | min | median | max | 20 | 50 | process at the max |", "|---|---|---|---|---|---|---|---|"]
    for g in groups:
        sel = [w for w in ws if w["group"] == g]
        top = [max(w["top"])[0] for w in sel]
        at = max(sel, key=lambda w: max(w["top"])[0])
        L.append(
            f"| {g} | {len(sel)} | {min(top):.1f} | {statistics.median(top):.1f} | {max(top):.1f} "
            f"| {sum(t >= 20 for t in top)} | {sum(t >= 50 for t in top)} "
            f"| `{max(at['top'])[1]}` ({at['run']}, cycle {at['cycle']}, {at['condition']}) |"
        )
    rises = sorted(
        ((w["load"][0] - prev["load"][0], prev, w) for prev, w in zip(ws, ws[1:]) if prev["run"] == w["run"]),
        key=lambda r: -r[0],
    )[:5]
    L += ["", "## Largest rises in the 1 minute load between consecutive samples of a run", "",
          "A rise spans one window and the idle after it. The load average includes the run's own threads.", "",
          "| run | window spanned | 1 min load, before it to before the next window | rise | the next window |",
          "|---|---|---|---|---|"]
    for rise, prev, w in rises:
        state = {None: "", True: ", slow", False: ", normal"}[w["slow"]]
        L.append(
            f"| {prev['run']} | cycle {prev['cycle']}, {prev['condition']} "
            f"| {prev['load'][0]:.2f} to {w['load'][0]:.2f} | +{rise:.2f} | cycle {w['cycle']}, {w['condition']}{state} |"
        )
    L += ["", "## PB-R's hetero windows, each sample", "",
          "| run | cycle | short P99 ms | state | 1 min load | top five, `%cpu` |", "|---|---|---|---|---|---|"]
    for w in ws:
        if w["cell"] == "PB-R" and w["condition"] == "hetero":
            top = ", ".join(f"{n} {pct:.1f}" for pct, n in w["top"])
            L.append(
                f"| {w['run']} | {w['cycle']} | {w['p99']:.2f} | {'slow' if w['slow'] else 'normal'} "
                f"| {w['load'][0]:.2f} | {top} |"
            )
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if background.md is stale")
    ap.add_argument("--raw", type=Path, default=EXP / "raw")
    ap.add_argument("--out", type=Path, default=EXP)
    a = ap.parse_args()
    ws = windows(a.raw)
    if not ws:
        sys.exit(f"no raw runs in {a.raw}: fetch the files listed in evidence.json first")
    md = tables(ws)
    target = a.out / "background.md"
    if a.check:
        if not target.exists() or target.read_text() != md:
            sys.exit("stale: ['background.md']")
        print("background.md is up to date")
        return
    target.write_text(md)
    print(md)


if __name__ == "__main__":
    main()
